### ISSUE TITLE
TypeError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by bkandel-edf** [fcollonval/jupyter_conda#16]
Hi,

I have jut installed the latest version of jupyter_conda with JupyterLab 1.1.0.
Executing _jupyter labextension list_ in an anaconda prompt confirms the required extensions are installed and enabled:
        jupyterlab_conda v1.0.0 enabled  ok
        jupyterlab_toastify v2.3.0 enabled  ok
Executing conda list in the anaoconda prompt confirms I have the conda package installed:
       jupyter_conda             2.4.1                 py37_1000    conda-forge
however I get the following error when running jupyter lab:
"TypeError: Unexpected token < in JSON at position 0"
And the environments I have are not listed.
If I switch to Jupyter Notebook by changing /lab to /tree in the URL, I can confirm that the conda extension works correctly in Jupyter Notebook (The environments are listed correctly).

Any idea waht is happening?

Thanks,

**Comment by fcollonval** [comment]
Hey Benjamin, the latest version of the extension requires `jupyter_conda` v3. Could you try updating it with `pip` or `conda`?

**Comment by bkandel-edf** [comment]
Hi,

Problem solved after updating to jupyter_conda 3.0.0.
Thank you!
Benjamin
