### ISSUE TITLE
Support for Jupyterlab 2.0.1 

### ISSUE THREAD

**Issue by adragoset** [fcollonval/jupyter_conda#28]
HI i was wondering if there will be support for the current version of jupyterlab. It looks like the plugin is pinned to jupyterlab 1.0.0

**Comment by fcollonval** [comment]
@adragoset Thank you for reaching out. 

Yes, this is on my (too long) todo list. 
Contributions are welcomed, so do not hesitate to propose a PR.

**Comment by fcollonval** [comment]
[jupyterlab_conda@2.0.0](https://www.npmjs.com/package/jupyterlab_conda) for JupyterLab 2.0 has been released.
