### ISSUE TITLE
Click 'Conda Packages Manager' in 'Settings' has no effect

### ISSUE THREAD

**Issue by corralm** [fcollonval/jupyter_conda#35]
## Description
Clicking `Settings` >> `Conda Packages Manager` doesn't do anything. Expected to open the packages manager.

Tried uninstalling & reinstallling both `jupyterlab_conda` and `jupyterlab_toastify` with the same result.

I believe the issue has something to do with the output below after entering `jupyter lab` in command line:  
- \[jupyter_conda] No available packages list in cache [Errno 2] No such file or directory: '/var/folders/c_/9bhvtjtn47l_2756zh7fny880000gn/T/jupyter_conda_packages.json'.

Oddly, I'm able to locate this file.

- Python package version: Python 3.7.7

- Extension version: 3.2.0

- General information:
JupyterLab v2.1.2
Known labextensions:
   app dir: /Users/miguel/anaconda3/envs/dev/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.2.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/github v2.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @krassowski/jupyterlab_go_to_definition v1.0.0  enabled  OK
        jupyterlab-execute-time v1.0.0  enabled  OK
        jupyterlab_conda v2.0.0  enabled  OK
        jupyterlab_toastify v3.0.0  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

- conda info results:
active environment : dev
active env location : /Users/miguel/anaconda3/envs/dev
shell level : 2
user config file : /Users/miguel/.condarc
populated config files : /Users/miguel/.condarc
conda version : 4.8.3
conda-build version : 3.18.9
python version : 3.7.4.final.0
virtual packages : __osx=10.15.4
base environment : /Users/miguel/anaconda3  (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/osx-64
https://repo.anaconda.com/pkgs/r/noarch
package cache : /Users/miguel/anaconda3/pkgs
/Users/miguel/.conda/pkgs
envs directories : /Users/miguel/anaconda3/envs
/Users/miguel/.conda/envs
platform : osx-64
user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.4 Darwin/19.4.0 OSX/10.15.4
UID:GID : 501:20
netrc file : /Users/miguel/.netrc
offline mode : False
<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
\[I 20:18:26.693 LabApp\] \[nb\_conda\_kernels\] enabled, 1 kernels found

\[I 20:18:27.225 LabApp\] The port 8888 is already in use, trying another port.

\[I 20:18:27.240 LabApp\] \[jupyter\_conda\] enabled

\[I 20:18:27.269 LabApp\] \[jupyter\_nbextensions\_configurator\] enabled 0.4.1

\[I 20:18:28.114 LabApp\] JupyterLab extension loaded from /Users/miguel/anaconda3/envs/dev/lib/python3.7/site-packages/jupyterlab

\[I 20:18:28.114 LabApp\] JupyterLab application directory is /Users/miguel/anaconda3/envs/dev/share/jupyter/lab

\[I 20:18:28.226 LabApp\] Serving notebooks from local directory: /Users/miguel

\[I 20:18:28.226 LabApp\] The Jupyter Notebook is running at:

\[I 20:18:28.226 LabApp\] http://localhost:8889/?token=c909331d21392b7b8b782ee202ba64f97af6aeef6b8c051f

\[I 20:18:28.226 LabApp\] or http://127.0.0.1:8889/?token=c909331d21392b7b8b782ee202ba64f97af6aeef6b8c051f

\[I 20:18:28.226 LabApp\] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

\[C 20:18:28.234 LabApp\]  

To access the notebook, open this file in a browser:

file:///Users/miguel/Library/Jupyter/runtime/nbserver-8760-open.html

Or copy and paste one of these URLs:

http://localhost:8889/?token=c909331d21392b7b8b782ee202ba64f97af6aeef6b8c051f

or http://127.0.0.1:8889/?token=c909331d21392b7b8b782ee202ba64f97af6aeef6b8c051f

\[W 20:18:32.059 LabApp\] 404 GET /github?1589080711869 (::1) 134.55ms referer=http://localhost:8889/lab

\[I 20:18:35.406 LabApp\] Build is up to date

\[jupyter\_conda\] No available packages list in cache \[Errno 2\] No such file or directory: '/var/folders/c\_/9bhvtjtn47l\_2756zh7fny880000gn/T/jupyter\_conda\_packages.json'.
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
Not sure how to do this...
</details>

**Comment by fcollonval** [comment]
Hey @corralm thanks for the detail description.

Could you clean your JupyterLab workspaces?

For that,

1. Locate the workspace directory by executing

```
jupyter lab path
```

2. Remove all files in the *Workspaces directory*

Let me know if it worked.

**Comment by corralm** [comment]
Awesome, it worked. Thanks, I love this tool!
