### ISSUE TITLE
Error while listing Conda environments

### ISSUE THREAD

**Issue by DoWalther** [fcollonval/jupyter_conda#44]
## Description
I installed jupyterlab_conda and jupyterlab_toastify on a fresh miniconda environment. When starting the JupyterLab server the extensions says it is loading all packages in the background. So far so good. When i open the Conda Packages Manager via the Settings menu a new field "An error occurred while listing Conda environments." shows up and nothing happens. 

## Reproduce
Open the Conda Packages Manager via the Settings dropdown menu in JupyterLab.

## Expected behavior
List all environments and the installed packages.

## Context
- Python package version:

jupyter_conda             3.3.1              pyh9f0ad1d_0    conda-forge

- Extension version:

JupyterLab v2.1.3
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @lckr/jupyterlab_variableinspector v0.5.0  enabled  OK
        jupyterlab_conda v2.1.2  enabled  OK
        jupyterlab_toastify v4.0.0  enabled  OK

- General information:

    active environment : base
    active env location : /opt/conda
                   shell level : 1
           user config file : /root/.condarc
populated config files : /opt/conda/.condarc
             conda version : 4.8.3
   conda-build version : not installed
            python version : 3.7.6.final.0
          virtual packages : __glibc=2.27
        base environment : /opt/conda  (writable)
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                                         https://conda.anaconda.org/conda-forge/noarch
                                         https://repo.anaconda.com/pkgs/main/linux-64
                                         https://repo.anaconda.com/pkgs/main/noarch
                                         https://repo.anaconda.com/pkgs/r/linux-64
                                         https://repo.anaconda.com/pkgs/r/noarch
             package cache : /opt/conda/pkgs
                                         /root/.conda/pkgs
           envs directories : /opt/conda/envs
                                        /root/.conda/envs
                       platform : linux-64
                   user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.9.184-linuxkit ubuntu/18.04.3 glibc/2.27
                        UID:GID : 0:0
                       netrc file : None
                  offline mode : False

<details><summary>Command Line Output</summary>
<pre>
[I 09:20:26.947 LabApp] 302 GET / (172.17.0.1) 2.92ms
[jupyter_conda] No available packages list in cache.
[E 09:20:30.369 LabApp] [jupyter_conda] Error for task {'type': 'AttributeError', 'error': "'EnvManager' object has no attribute 'list_available'", 'message': 'AttributeError("\'EnvManager\' object has no attribute \'list_available\'")', 'traceback': ['  File "/opt/conda/lib/python3.7/site-packages/jupyter_conda/handlers.py", line 99, in execute_task\n    result = await f(*args)\n', '  File "/opt/conda/lib/python3.7/site-packages/jupyter_conda/handlers.py", line 376, in update_available\n    answer = await env_manager.list_available()\n']}.
[I 09:20:32.144 LabApp] Build is up to date
[E 09:20:32.148 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0",
      "Accept": "*/*",
      "Accept-Language": "de,en-US;q=0.7,en;q=0.3",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab?",
      "Authorization": "token 371d84163c690ff5e36733aba7156d2fe1a292b1df8a65c0",
      "X-Xsrftoken": "2|50d45677|d0c6fb53aeb59c0aa1faa2c7c1a33674|1590739972",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|50d45677|d0c6fb53aeb59c0aa1faa2c7c1a33674|1590739972; username-localhost-8888=\"2|1:0|10:1590744030|23:username-localhost-8888|44:NDczMTA3OTk5YjA1NDZiNmFkMTMyZDZkMzgxNDAzNjE=|6cd51c01980db7be6def68589ba326cd90e2b880880919eaa4d0f6305c989853\"",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 09:20:32.149 LabApp] 500 GET /conda/tasks/1?1590744031373 (172.17.0.1) 4.29ms referer=http://localhost:8888/lab?
[E 09:21:40.253 LabApp] Uncaught exception GET /conda/environments?whitelist=0&1590744100227 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/conda/environments?whitelist=0&1590744100227', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/jupyter_conda/handlers.py", line 174, in get
        list_envs = await self.env_manager.list_envs(whitelist == 1)
    TypeError: list_envs() takes 1 positional argument but 2 were given
[W 09:21:40.274 LabApp] Unhandled error
</pre>
</details>

**Comment by fcollonval** [comment]
Hey @DoWalther thanks for the detailed description. Your error is quite surprising. It looks like the Python code is not up-to-date.

Could you try/check the following actions in that order:
1. Execute `jupyter serverextension list` to check jupyter_conda used is v3.3.1
2. Could you open the file /opt/conda/lib/python3.7/site-packages/jupyter_conda/envmanager.py and check that on line 311, you have the following code:
```py
    async def list_envs(
        self, whitelist: bool = False
    ) -> Dict[str, List[Dict[str, Union[str, bool]]]]:
```
3. If 1 or 2 are not correct, you can try reinstalling the python package:
```
conda install -c conda-forge --force-reinstall jupyter_conda=3.3.1
```
4. Test the extension alone on a new environment:
```
conda create -c conda-forge -n test-jconda -y jupyterlab=2 jupyter_conda=3.3.1
conda activate test-jconda
jupyter labextension install jupyterlab_conda@2.1.2
```

**Comment by BDimitri** [comment]
Hello,
I am a colleague of DoWalther and am working with the same system.
First of all, thanks for all the suggestions. I followed your steps 1 and 2, both show the correct version numbers and code. When trying to install the extension in an new environment my JupyterLab Terminal simply crashed and the tab was closed.
To make reproduction easier I created a dockerfile for people who are willing to try for themselves: [https://pastebin.com/VaNbTDLK](https://pastebin.com/VaNbTDLK) (Note: this version installs python 3.8, but the same error occurs with 3.7).
To test this simply build the image, start a container from this image with port forwarding `-p 8888:8888` and see for yourself in your browser by visiting `http://localhost:8888/lab/`in your browser.
I also added the dockerfile as .txt due to github upload restrictions.
[mini_example.txt](https://github.com/fcollonval/jupyter_conda/files/4722457/mini_example.txt)

**Comment by fcollonval** [comment]
Hey, thanks for the dockerfile.

You get a conflict because you are installing [nb_conda](https://github.com/Anaconda-Platform/nb_conda) and this extension. This work starts as a fork of nb_conda. Therefore the rest API is identical. So the JupyterLab extension calls to the server ends up mixing between the code of the two extensions.

So the short answer is drop installing nb_conda.

> Note: your intent may have been to install [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels)

**Comment by DoWalther** [comment]
Hey @fcollonval,
thanks for your help! In deed, uninstalling nb_conda works. Now everything looks right and functions correctly.

**Comment by jim-tty** [comment]
An error occurred while listing Conda environments.
Internal Server Error

help!!! I don't find this error's answer! omg!!!

**Comment by fcollonval** [comment]
@jim-tty would you mind starting a new issue and provide as much information as possible (like the server log)?
