### ISSUE TITLE
Kernel spec metadata discard existing fields

### ISSUE THREAD

**Issue by jtpio** [fcollonval/jupyter_conda#45]
## Description

It looks like the original kernel spec metadata for a kernel is not kept when using the "conda version" of the kernel.

## Reproduce

1. Go to mybinder.org: https://mybinder.org/v2/gh/fcollonval/jupyter_conda/master?urlpath=lab
2. Install `xeus-python` from the conda packages manager
3. Do a `GET /api/kernelspecs` to retrieve the kernel specs (for example in the browser by entering: https://path/to/the/mybinder.org/api/kernelspecs)

Starting from version `0.8.0`, `xeus-python` includes the `debugger` key in the kernel specs metadata.

However this key is not present in the metadata for `xpython [conda env:notebook] *`:

![image](https://user-images.githubusercontent.com/591645/85113888-4ed89f00-b218-11ea-94a8-c8336d224348.png)

## Expected behavior

The `metadata` for `xpython [conda env:notebook] *` should include `debugger: true` along `conda_env_name` and `conda_env_path`.

## Context

Binder link on Firefox 77.

**Comment by jtpio** [comment]
It looks like this actually comes from the underlying `nb_conda_kernels`?

https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L196-L199

```python
spec['metadata'] = {
    'conda_env_name': env_name,
    'conda_env_path': env_path
}
```

**Comment by fcollonval** [comment]
@jtpio Indeed this is a bug in nb_conda_kernels. The metadata was not around at the beginning. And when I wrote the PR adding the conda environment info to the metadata, I did not think about propagating the one from the reference kernel.

Could you open an issue in that repository?

**Comment by jtpio** [comment]
Thanks @fcollonval.

Yes I'll open an issue there :+1:

**Comment by fcollonval** [comment]
Thanks!

**Comment by jtpio** [comment]
Opened https://github.com/Anaconda-Platform/nb_conda_kernels/issues/160

**Comment by fcollonval** [comment]
A fix has been merged in the dependency package
https://github.com/Anaconda-Platform/nb_conda_kernels/pr/161

**Comment by jtpio** [comment]
Perfect, thanks a lot @fcollonval!
